### ISSUE TITLE
It works but its really buggy

### ISSUE THREAD

**Issue by devgz** [MarcAnt01/ARCore_enabler#2]
Is there a way to make it less buggy? It lags and doesnt work well. Any Test Apps?

**Comment by MarcAnt01** [comment]
What are you talking about? My module ENABLES SUPPORT, does have nothing to do with APPS LAGGING OR MISBEHAVING. If you are talking about Playground happens on low-end or old devices, in fact it's just thought for recent flagships. I mean it will work anyway, but expect lags
