### ISSUE TITLE
Link download not working

### ISSUE THREAD

**Issue by waelnoaman** [MarcAnt01/ARCore_enabler#3]
Downloads not working

**Comment by MarcAnt01** [comment]
They are working
![Screenshot_Chrome_20190429-184857](https://user-images.githubusercontent.com/43090263/56912484-a6b1c500-6aaf-11e9-98ca-60f848c4af93.png)

**Comment by waelnoaman** [comment]
I will try again

**Comment by MarcAnt01** [comment]
OK, lemme know if something goes wrong

**Comment by waelnoaman** [comment]
Working Sir when i open vpn
