### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by waelnoaman** [MarcAnt01/ARCore_enabler#4]
Dear Sir 

Did you will release new version from Arcore enabler as i see 

Latest commit by MarcAnt01 1 day ago

Can u share latest stable version link to download 

Thanks
Adel

**Comment by MarcAnt01** [comment]
Since now, the module will be updated through Magisk Repository, just look for it Manager. In case you want to take a look to the Repo, check [here](https://github.com/Magisk-Modules-Repo/ARCore_enabler)
